### ISSUE TITLE
Person2.java possible array index out of bounds

### ISSUE THREAD

**Issue by mkrupczak3** [josh75337/CS-2340-Blockchain-Beach-Boys-M2#2]
There is a possibility for an array index out of bounds in Person2.java

if the index variable is randomly selected to be the last index when there is something already there, the index will increment past the end, and the program will attempt to write randArr[index] while index is out of bounds. 

Also if the index random int is larger than the length of the input string, an index out of bounds will occur as well. 

to fix this, it may be necessary to do randArr[index % input.length()] in the while loop conditional and the assignment directly after it.

**Comment by mchan60** [comment]
should be fixed
